Revert lockfile after tests
sparksuite/rugged pull request #72
Opened 2021-06-10 18:50 UTC by corymharper

This pull request introduces a new util function that is used in the first step of rugged to store a copy of the lockfile for a project before we do anything, and in the last step to restore it after all testing is completed.

Closes #71

2021-06-11 20:01 UTC, WesCossick requested changes, later dismissed

2021-06-11 20:01 UTC, WesCossick commented on src/steps/install-dependencies.test.ts
> +jest.mock('../utils/lockfile-manager.ts');
Let’s make this the same as the other lines:

```suggestion
jest.mock('../utils/lockfile-manager');
```

2021-06-11 20:01 UTC, WesCossick commented on src/utils/lockfile-manager.ts
> +const lockfileManager = {
Why call this the lockfile “manager?” Why not just “lockfile” instead, since it’s focused on the lockfile itself?

2021-06-11 20:01 UTC, WesCossick commented on src/utils/lockfile-manager.ts
> +	storeLockfile: (absolutePath: string): void => {
If you rename the object/file/etc. to just “lockfile,” then you can just call this `store`.

2021-06-11 20:01 UTC, WesCossick commented on src/utils/lockfile-manager.ts
> +	overwriteLockfile: (absolutePath: string): void => {
See comment above. Can rename to just `overwrite`.

2021-06-11 20:01 UTC, WesCossick commented on src/utils/lockfile-manager.ts
> +/** Helper functions to preserve a lockfile */
This comment is in the wrong place it seems. Also, the functions inside the object need TS Doc (`/** */`) comments too.

2021-06-11 20:02 UTC, WesCossick commented
Also, are you also reverting any changes to the `node_modules/` directory? Because if the lockfile gets updated, just reverting the changes to that file won’t actually change what’s in the the `node_modules/` directory.

2021-06-14 15:15 UTC, corymharper commented on src/utils/lockfile-manager.ts
> +const lockfileManager = {
`lockfile` probably works, I was looking at the `package-manager.ts` and thinking that it was similar in some ways, so I tried to name them consistently.

2021-06-14 15:20 UTC, corymharper commented
> Also, are you also reverting any changes to the `node_modules/` directory? Because if the lockfile gets updated, just reverting the changes to that file won’t actually change what’s in the the `node_modules/` directory.

I am running the install command after reverting the lockfile with the frozen lockfile flag, in npm's case I'm running `npm ci`, you can see that in action on the following and subsequent lines: https://github.com/sparksuite/rugged/pull/72/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R90

I thought that seemed sufficient to be confident I was restoring the previous state of the node modules.

2021-06-15 21:03 UTC, WesCossick commented
> > Also, are you also reverting any changes to the `node_modules/` directory? Because if the lockfile gets updated, just reverting the changes to that file won’t actually change what’s in the the `node_modules/` directory.
> 
> I am running the install command after reverting the lockfile with the frozen lockfile flag, in npm's case I'm running `npm ci`, you can see that in action on the following and subsequent lines: https://github.com/sparksuite/rugged/pull/72/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R90
> 
> I thought that seemed sufficient to be confident I was restoring the previous state of the node modules.

I think that _should_ be sufficient. Though you may want to do some tests to be sure. One way to test it would be to not ignore the `node_modules/` directory and see if Rugged first introduces changes and then eliminates those.

2021-07-09 15:48 UTC, WesCossick approved these changes
Looks good!

2021-07-09 15:53 UTC, merged